apiVersion: v1
kind: Pod
metadata:
  name: experiment
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
spec:
  initContainers:
    - name: git-clone
      image: alpine/git
      args:
        - clone
        - --single-branch
        - --
        - https://github.com/cdsap/Talaiot
        - /repo
      securityContext:
        runAsUser: 1
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
      volumeMounts:
        - name: git-repo
          mountPath: /repo
  containers:
    - name:  agent
      image: cdsap/navetesbase
      args: ['sleep', '100000']
      volumeMounts:
        - name: git-repo
          mountPath: /repo
      lifecycle:
            postStart:
              exec:
                command:
                - bash
                - -c
                - |
                  cd /repo
                  pwd >  /usr/share/message
                  ./gradlew clean > /usr/share/log
  volumes:
    - name: git-repo
      emptyDir: {}
